CREATE TABLE IF NOT EXISTS `inventoryimport` (
	`id` int NOT NULL AUTO_INCREMENT,
	`gtin` varchar(14),
	`product_type` varchar(256),
	`style_code` varchar(64) NOT NULL,
	`color_code` varchar(64),
	`color_description` varchar(64),
	`color_type` varchar(64),
	`size_code` varchar(64),
	`brand` varchar(256),
	`gender` varchar(64),
	`fit` varchar(64),
	`price` DECIMAL(6,2),
	`price_map` DECIMAL(6,2),
	`collection` varchar(256),
	`description_short` TEXT,
	`description_long` TEXT,
	`callouts` TEXT,
	`image_1` TEXT,
	`image_2` TEXT,
	`supplier` varchar(64) NOT NULL,
	`stock` int,
	`weight` DECIMAL(6,2),
	PRIMARY KEY (`id`)
) ENGINE=Aria;

CREATE TABLE IF NOT EXISTS `productexport` (
	`id` int NOT NULL AUTO_INCREMENT,
	`gtin` varchar(14) NOT NULL UNIQUE,
	`sku` varchar(256) NOT NULL UNIQUE,
	`name` varchar(256) NOT NULL,
	`short_description` varchar(256) NOT NULL,
	`description` TEXT NOT NULL,
	`categories` varchar(1024),
	`url_key` varchar(256) NOT NULL,
	`price` DECIMAL(6,2) NOT NULL,
	`base_image` TEXT NOT NULL,
	`base_image_label` varchar(256) NOT NULL,
	`product_online` tinyint NOT NULL DEFAULT '0',
	`attribute_set_code` varchar(64) NOT NULL DEFAULT 'Default',
	`additional_attributes` varchar(1024),
	`weight` DECIMAL(6,2) NOT NULL,
	`qty` int NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=Aria;
